export type BlogPostPreview = {
  id: string;
  title: string;
  category: string;
  excerpt: string;
  displayDate: string;
  publishedAt: string;
  dateModified: string;
  readTime: string;
  author: string;
  coverLabel: string;
  image: string;
  imageAlt: string;
  blurDataURL?: string;
};

const author = "qwevo tv editorial team";

export const postPreviews: BlogPostPreview[] = [
  {
    id: "smart-tv-iptv-setup-guide",
    title: "How to set up qwevo tv on Smart TV in 2026",
    category: "Setup",
    excerpt: "A complete Smart TV setup guide for Samsung, LG, and Android TV users who want a clean IPTV experience.",
    displayDate: "Jun 3, 2026",
    publishedAt: "2026-06-03T09:00:00Z",
    readTime: "10 min",
    coverLabel: "Smart TV setup",
    image: "/images/blog/smart-tv-iptv-setup-guide-1280.webp",
    imageAlt: "Modern Smart TV streaming interface in a living room for qwevo tv setup",
    author,
    dateModified: "2026-06-03T09:00:00Z",
  },
  {
    id: "fire-stick-iptv-setup-guide",
    title: "qwevo tv on Fire Stick: a complete setup and performance guide",
    category: "Devices",
    excerpt: "Learn how to prepare a streaming stick, choose a lightweight player, and keep qwevo tv smooth on a TV.",
    displayDate: "Jun 1, 2026",
    publishedAt: "2026-06-01T09:00:00Z",
    readTime: "10 min",
    coverLabel: "Fire Stick setup",
    image: "/images/blog/fire-stick-iptv-setup-guide-1280.webp",
    imageAlt: "Television streaming setup with remote and compact device for Fire Stick IPTV setup",
    author,
    dateModified: "2026-06-01T09:00:00Z",
  },
  {
    id: "stop-iptv-buffering",
    title: "How to stop IPTV buffering on qwevo tv",
    category: "Troubleshooting",
    excerpt: "A practical buffering checklist for network, device, player, and support issues on qwevo tv.",
    displayDate: "May 28, 2026",
    publishedAt: "2026-05-28T09:00:00Z",
    readTime: "11 min",
    coverLabel: "Buffering fix",
    image: "/images/blog/stop-iptv-buffering-1280.webp",
    imageAlt: "Mobile and TV streaming setup used for qwevo tv buffering troubleshooting",
    author,
    dateModified: "2026-05-28T09:00:00Z",
  },
  {
    id: "iptv-pricing-guide",
    title: "How to compare IPTV pricing without getting lost",
    category: "Buying guide",
    excerpt: "Compare IPTV plans by device count, support quality, duration, and real monthly value.",
    displayDate: "May 24, 2026",
    publishedAt: "2026-05-24T09:00:00Z",
    readTime: "9 min",
    coverLabel: "Pricing guide",
    image: "/images/blog/iptv-pricing-guide-1280.webp",
    imageAlt: "Person comparing IPTV subscription options on a laptop for qwevo tv pricing",
    author,
    dateModified: "2026-05-24T09:00:00Z",
  },
  {
    id: "watch-sports-on-iptv",
    title: "How to watch live sports on qwevo tv without stress",
    category: "Sports",
    excerpt: "Prepare your device, app, and connection before kickoff for a smoother live sports IPTV session.",
    displayDate: "May 20, 2026",
    publishedAt: "2026-05-20T09:00:00Z",
    readTime: "10 min",
    coverLabel: "Sports streaming",
    image: "/images/blog/watch-sports-on-iptv-1280.webp",
    imageAlt: "Live soccer match on a TV screen for qwevo tv sports streaming",
    author,
    dateModified: "2026-05-20T09:00:00Z",
  },
  {
    id: "android-tv-box-iptv-setup",
    title: "Best way to set up qwevo tv on an Android TV box",
    category: "Devices",
    excerpt: "Use an Android TV box for a flexible IPTV setup with better app choice, storage, and performance control.",
    displayDate: "May 16, 2026",
    publishedAt: "2026-05-16T09:00:00Z",
    readTime: "10 min",
    coverLabel: "Android TV box",
    image: "/images/blog/android-tv-box-iptv-setup-1280.webp",
    imageAlt: "Streaming devices and television setup for qwevo tv Android TV box IPTV",
    author,
    dateModified: "2026-05-16T09:00:00Z",
  },
  {
    id: "iptv-on-iphone-ipad",
    title: "How to use qwevo tv on iPhone and iPad",
    category: "Mobile",
    excerpt: "A mobile IPTV guide for users who want qwevo tv on iPhone, iPad, and secondary screens.",
    displayDate: "May 12, 2026",
    publishedAt: "2026-05-12T09:00:00Z",
    readTime: "9 min",
    coverLabel: "Mobile setup",
    image: "/images/blog/iptv-on-iphone-ipad-1280.webp",
    imageAlt: "Phone and tablet streaming setup for watching qwevo tv on mobile devices",
    author,
    dateModified: "2026-05-12T09:00:00Z",
  },
  {
    id: "choose-right-iptv-provider",
    title: "How to choose the right IPTV provider in 2026",
    category: "Buying guide",
    excerpt: "Use this practical checklist to evaluate IPTV providers by clarity, support, device fit, and trust.",
    displayDate: "May 8, 2026",
    publishedAt: "2026-05-08T09:00:00Z",
    readTime: "11 min",
    coverLabel: "Provider checklist",
    image: "/images/blog/choose-right-iptv-provider-1280.webp",
    imageAlt: "Person reviewing streaming provider options on a laptop for qwevo tv buying guide",
    author,
    dateModified: "2026-05-08T09:00:00Z",
  },
  {
    id: "understand-iptv-features",
    title: "What IPTV features actually matter in everyday use",
    category: "Features",
    excerpt: "Separate useful IPTV features from marketing noise so you can choose what improves real viewing.",
    displayDate: "May 4, 2026",
    publishedAt: "2026-05-04T09:00:00Z",
    readTime: "9 min",
    coverLabel: "Feature guide",
    image: "/images/blog/understand-iptv-features-1280.webp",
    imageAlt: "Family using TV and mobile devices for qwevo tv multi device IPTV features",
    author,
    dateModified: "2026-05-04T09:00:00Z",
  },
  {
    id: "iptv-support-and-troubleshooting",
    title: "qwevo tv support and troubleshooting guide",
    category: "Support",
    excerpt: "Learn what information to send, when to use support, and how to solve common IPTV setup problems faster.",
    displayDate: "May 1, 2026",
    publishedAt: "2026-05-01T09:00:00Z",
    readTime: "10 min",
    coverLabel: "Support guide",
    image: "/images/blog/iptv-support-and-troubleshooting-1280.webp",
    imageAlt: "Customer support agent with headset for qwevo tv IPTV troubleshooting help",
    author,
    dateModified: "2026-05-01T09:00:00Z",
  },
  {
    id: "iptv-smarters-pro-firestick-setup",
    title: "How to Install IPTV Smarters Pro on Firestick (2026 Complete Guide)",
    category: "IPTV Apps",
    excerpt: "Step-by-step guide to sideload IPTV Smarters Pro on Firestick. Includes APK download, installation, login setup, EPG config, and performance optimization tips.",
    displayDate: "Jun 18, 2026",
    publishedAt: "2026-06-18T09:00:00Z",
    readTime: "14 min",
    coverLabel: "Smarters on Firestick",
    image: "/images/blog/iptv-smarters-pro-firestick-setup-1280.webp",
    imageAlt: "IPTV Smarters Pro interface displayed on a television with Firestick remote controller",
    author,
    dateModified: "2026-06-18T09:00:00Z",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkABUB8JQBOgBb1nF1YAAD+0GltcP+CwDO25vpz2CaKlH7nQ2URcj18/HP0kRD9J9CyNd6bx2VjeGbl54OrIAA=",
  },
  {
    id: "fix-iptv-buffering-2026",
    title: "How to Fix IPTV Buffering Issues: Complete Troubleshooting Guide (2026)",
    category: "IPTV Technology",
    excerpt: "Comprehensive guide to diagnosing and fixing IPTV buffering. Covers internet speed, Ethernet vs Wi-Fi, DNS, buffer size, hardware acceleration, VPN, QoS, and more.",
    displayDate: "Jun 18, 2026",
    publishedAt: "2026-06-18T09:00:00Z",
    readTime: "15 min",
    coverLabel: "Buffering guide",
    image: "/images/blog/fix-iptv-buffering-2026-1280.webp",
    imageAlt: "Network speed test on a smartphone next to a streaming television for IPTV buffering troubleshooting",
    author,
    dateModified: "2026-06-18T09:00:00Z",
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkABUB8JbACdADxKyHZgAD+405DMEF+5HnkYRqZOb5+6wI+RPhSh1h0N3tfymE7OTfZNS3cIqMHdPhXdhFGt1NAxFuAAAA=",
  },
  {
    id: "tivimate-setup-guide",
    title: "TiviMate IPTV Player Setup: The Complete Guide for Firestick & Android TV (2026)",
    category: "IPTV Apps",
    excerpt: "Step-by-step guide to install and configure TiviMate on Firestick and Android TV. Covers sideloading, playlist setup, EPG config, performance tuning, and advanced features.",
    displayDate: "Jun 25, 2026",
    publishedAt: "2026-06-25T09:00:00Z",
    readTime: "14 min",
    coverLabel: "TiviMate setup",
    image: "/images/blog/tivimate-setup-guide-1280.webp",
    imageAlt: "TiviMate IPTV player interface on a television screen with streaming channel guide displayed",
    author,
    dateModified: "2026-06-25T09:00:00Z",
  },
  {
    id: "best-vpn-for-iptv",
    title: "Best VPNs for IPTV Streaming in 2026: Expert Comparison & Setup Guide",
    category: "IPTV Technology",
    excerpt: "Comprehensive guide to choosing and setting up a VPN for IPTV. Compare NordVPN, ExpressVPN, and Surfshark for streaming performance, privacy, and value.",
    displayDate: "Jun 20, 2026",
    publishedAt: "2026-06-20T09:00:00Z",
    readTime: "12 min",
    coverLabel: "VPN guide",
    image: "/images/blog/best-vpn-for-iptv-1280.webp",
    imageAlt: "Laptop with security lock icon next to a streaming television for IPTV VPN setup",
    author,
    dateModified: "2026-06-20T09:00:00Z",
  },
  {
    id: "iptv-for-beginners-complete-guide",
    title: "IPTV for Beginners: Complete Guide to Getting Started in 2026",
    category: "Guide",
    excerpt: "Learn everything you need to know about IPTV in 2026: what it is, what equipment you need, how to choose a provider, and step-by-step setup on any device.",
    displayDate: "Jul 1, 2026",
    publishedAt: "2026-07-01T09:00:00Z",
    readTime: "15 min",
    coverLabel: "Beginner guide",
    image: "/images/blog/iptv-for-beginners-complete-guide-1280.webp",
    imageAlt: "Person browsing IPTV channel guide on a modern television in a cozy living room",
    author,
    dateModified: "2026-07-01T09:00:00Z",
  },
  {
    id: "complete-iptv-troubleshooting-guide",
    title: "How to Fix Common IPTV Problems: Complete Troubleshooting Guide (2026)",
    category: "Performance",
    excerpt: "Step-by-step solutions to every common IPTV problem: buffering, freezing, channels not loading, audio sync issues, login failures, and device-specific fixes.",
    displayDate: "Jul 3, 2026",
    publishedAt: "2026-07-03T09:00:00Z",
    readTime: "15 min",
    coverLabel: "Troubleshooting guide",
    image: "/images/blog/complete-iptv-troubleshooting-guide-1280.webp",
    imageAlt: "Technical troubleshooting setup with streaming device and network tools for IPTV problem solving",
    author,
    dateModified: "2026-07-03T09:00:00Z",
  },
];
